LOCAL_PATH:= $(call my-dir)
 
 
include $(CLEAR_VARS)
 
LOCAL_MODULE_TAGS := eng
LOCAL_SRC_FILES:=vl6180_test.c
LOCAL_MODULE:=vl6180_test
LOCAL_CPPFLAGS += -DANDROID
LOCAL_SHARED_LIBRARIES:=libc
LOCAL_STATIC_LIBRARIES := 
LOCAL_C_INCLUDES += $(LOCAL_PATH) $(LOCAL_PATH)/$(KERNEL_DIR)/include
include $(BUILD_EXECUTABLE)
 
 

